### ISSUE TITLE
Rewrite Outline Client's Routing for Linux

### ISSUE THREAD

**Issue by jyyi1** [Jigsaw-Code/outline-apps#2312]
#### TODO Items

- [x] Routing Logic PoC
- [x] TCP Traffic Routing
- [x] UDP Traffic Routing
- [x] Handling concurrency
- [x] IPv4 Traffic Routing
- [x] Initial Connectivity Check
- [ ] IPv6 Traffic Routing (another PR)
- [ ] Refresh UDP connectivity (another PR)
- [ ] Network Change Monitor (another PR)
- [ ] Network Change Connectivity Check (another PR)
- [ ] Delete old routing service code (another PR)
- [ ] Handle cancellation gracefully (another PR)

_Originally posted by @jyyi1 in https://github.com/Jigsaw-Code/outline-apps/issues/2291#issuecomment-2518743663_

**Comment by mars-json** [comment]
Hello! Any news when we can expect Outline client (for Linux) integrated with Network Manager?

**Comment by jyyi1** [comment]
Hi @mars-json ,

We've already migrated all routing logic to NetworkManager.

Please try the latest Outline Client: https://support.google.com/outline/answer/15331527

Note: The AppImage is deprecated and does not support NetworkManager.
